steps:
  - uses: actions/checkout@v3

  - uses: codfish/semantic-release-action@v3
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  - name: Install dependencies
    run: npm install
  - name: Build
    run: npm run build
  - name: Run semantic-release
    run: npx semantic-release